import pytest

from app.domain.pets import PetCreate, PetUpdate
from app.repositories.pet_repository import SqlaPetRepository


class TestAddPet:
    """Tests for SqlaPetRepository.add_pet()"""

    @pytest.mark.asyncio
    async def test_add_pet_persists_and_returns_pet(self, repository: SqlaPetRepository) -> None:
        """Test successfully adding a pet and verifying persistence."""
        payload = PetCreate(
            name="Milo", species="cat", breed="Siamese", color="cream", owner_name="Charlie", age=3
        )

        pet = await repository.add_pet(payload)

        assert pet.id is not None
        assert pet.name == "Milo"
        assert pet.species == "cat"
        assert pet.breed == "Siamese"
        assert pet.color == "cream"
        assert pet.owner_name == "Charlie"
        assert pet.age == 3

    @pytest.mark.asyncio
    async def test_add_pet_returns_pet_with_generated_id(
        self, repository: SqlaPetRepository
    ) -> None:
        """Test that added pet has an ID generated by the database."""
        payload = PetCreate(
            name="Whiskers",
            species="dog",
            breed="Golden Retriever",
            color="golden",
            owner_name="David",
            age=2,
        )

        pet = await repository.add_pet(payload)

        assert pet.id > 0


class TestGetPets:
    """Tests for SqlaPetRepository.get_pets()"""

    @pytest.mark.asyncio
    async def test_get_pets_returns_all_pets(self, repository: SqlaPetRepository) -> None:
        """Test retrieving all pets from the repository."""
        await repository.add_pet(
            PetCreate(
                name="Milo",
                species="cat",
                breed="Siamese",
                color="cream",
                owner_name="Charlie",
                age=3,
            )
        )
        await repository.add_pet(
            PetCreate(
                name="Bolt",
                species="dog",
                breed="Golden Retriever",
                color="golden",
                owner_name="David",
                age=5,
            )
        )

        pets = await repository.get_pets()

        assert len(pets) == 2
        assert {pet.name for pet in pets} == {"Milo", "Bolt"}

    @pytest.mark.asyncio
    async def test_get_pets_returns_empty_list_when_no_pets(
        self, repository: SqlaPetRepository
    ) -> None:
        """Test retrieving pets when none exist."""
        pets = await repository.get_pets()

        assert pets == []
        assert len(pets) == 0


class TestGetPet:
    """Tests for SqlaPetRepository.get_pet()"""

    @pytest.mark.asyncio
    async def test_get_pet_returns_matching_pet(self, repository: SqlaPetRepository) -> None:
        """Test retrieving a specific pet by ID."""
        created_pet = await repository.add_pet(
            PetCreate(
                name="Milo",
                species="cat",
                breed="Siamese",
                color="cream",
                owner_name="Charlie",
                age=3,
            )
        )

        pet = await repository.get_pet(created_pet.id)

        assert pet is not None
        assert pet.id == created_pet.id
        assert pet.name == "Milo"
        assert pet.species == "cat"

    @pytest.mark.asyncio
    async def test_get_pet_returns_none_when_missing(self, repository: SqlaPetRepository) -> None:
        """Test retrieving a non-existent pet returns None."""
        pet = await repository.get_pet(999)

        assert pet is None


class TestUpdatePet:
    """Tests for SqlaPetRepository.update_pet()"""

    @pytest.mark.asyncio
    async def test_update_pet_updates_only_provided_fields(
        self, repository: SqlaPetRepository
    ) -> None:
        """Test updating only specific fields of an existing pet."""
        created_pet = await repository.add_pet(
            PetCreate(
                name="Milo",
                species="cat",
                breed="Siamese",
                color="cream",
                owner_name="Charlie",
                age=3,
            )
        )
        payload = PetUpdate(age=4)

        updated_pet = await repository.update_pet(created_pet.id, payload)

        assert updated_pet is not None
        assert updated_pet.id == created_pet.id
        assert updated_pet.name == "Milo"
        assert updated_pet.species == "cat"
        assert updated_pet.breed == "Siamese"
        assert updated_pet.color == "cream"
        assert updated_pet.owner_name == "Charlie"
        assert updated_pet.age == 4

    @pytest.mark.asyncio
    async def test_update_pet_updates_multiple_fields(self, repository: SqlaPetRepository) -> None:
        """Test updating multiple fields of an existing pet."""
        created_pet = await repository.add_pet(
            PetCreate(
                name="Milo",
                species="cat",
                breed="Siamese",
                color="cream",
                owner_name="Charlie",
                age=3,
            )
        )
        payload = PetUpdate(name="Mittens", age=5)

        updated_pet = await repository.update_pet(created_pet.id, payload)

        assert updated_pet is not None
        assert updated_pet.name == "Mittens"
        assert updated_pet.species == "cat"
        assert updated_pet.breed == "Siamese"
        assert updated_pet.color == "cream"
        assert updated_pet.owner_name == "Charlie"
        assert updated_pet.age == 5

    @pytest.mark.asyncio
    async def test_update_pet_returns_none_when_missing(
        self, repository: SqlaPetRepository
    ) -> None:
        """Test updating a non-existent pet returns None."""
        payload = PetUpdate(name="Ghost")

        updated_pet = await repository.update_pet(999, payload)

        assert updated_pet is None


class TestDeletePet:
    """Tests for SqlaPetRepository.delete_pet()"""

    @pytest.mark.asyncio
    async def test_delete_pet_removes_existing_pet(self, repository: SqlaPetRepository) -> None:
        """Test successfully deleting an existing pet."""
        created_pet = await repository.add_pet(
            PetCreate(
                name="Milo",
                species="cat",
                breed="Siamese",
                color="cream",
                owner_name="Charlie",
                age=3,
            )
        )

        deleted = await repository.delete_pet(created_pet.id)
        pet = await repository.get_pet(created_pet.id)

        assert deleted is True
        assert pet is None

    @pytest.mark.asyncio
    async def test_delete_pet_returns_false_when_missing(
        self, repository: SqlaPetRepository
    ) -> None:
        """Test deleting a non-existent pet returns False."""
        deleted = await repository.delete_pet(999)

        assert deleted is False
