import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.users import UserCreate, UserUpdate
from app.repositories.user_repository import SqlaUserRepository, UserIntegrityError


class TestAddUser:
    """Tests for SqlaUserRepository.add_user()."""

    @pytest.mark.asyncio
    async def test_add_user_persists_and_returns_user(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test successfully adding a user and verifying its returned fields."""
        # Arrange
        payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )

        # Act
        user = await user_repository.add_user(payload)

        # Assert
        assert user.id is not None
        assert user.username == "alice"
        assert user.email == "alice@example.com"
        assert user.full_name == "Alice Smith"
        assert user.disabled is False

    @pytest.mark.asyncio
    async def test_add_user_returns_user_with_generated_id(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test that an added user has an ID generated by the database."""
        # Arrange
        payload = UserCreate(
            username="bob",
            email="bob@example.com",
            full_name="Bob Jones",
            disabled=False,
            hashed_password="hashed-password",
        )

        # Act
        user = await user_repository.add_user(payload)

        # Assert
        assert user.id > 0

    @pytest.mark.asyncio
    async def test_add_user_raises_integrity_error_for_duplicate_username(
        self, user_repository: SqlaUserRepository, session: AsyncSession
    ) -> None:
        """Test that duplicate usernames are reported as repository integrity errors."""
        # Arrange
        existing_payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )
        duplicate_payload = UserCreate(
            username="alice",
            email="another@example.com",
            full_name="Another User",
            disabled=False,
            hashed_password="another-password",
        )

        # Act and Assert
        await user_repository.add_user(existing_payload)
        with pytest.raises(UserIntegrityError):
            await user_repository.add_user(duplicate_payload)


class TestGetUserCredentials:
    """Tests for SqlaUserRepository.get_user_credentials()."""

    @pytest.mark.asyncio
    async def test_get_user_credentials_returns_matching_credentials(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test retrieving credentials for a specific username."""
        # Arrange
        payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )

        # Act
        created_user = await user_repository.add_user(payload)
        credentials = await user_repository.get_user_credentials("alice")

        # Assert
        assert credentials is not None
        assert credentials.id == created_user.id
        assert credentials.username == "alice"
        assert credentials.email == "alice@example.com"
        assert credentials.hashed_password == "hashed-password"

    @pytest.mark.asyncio
    async def test_get_user_credentials_returns_none_when_missing(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test retrieving credentials for a non-existent username."""
        # Act
        credentials = await user_repository.get_user_credentials("missing")

        # Assert
        assert credentials is None


class TestGetUserByUsername:
    """Tests for SqlaUserRepository.get_user_by_username()."""

    @pytest.mark.asyncio
    async def test_get_user_by_username_returns_matching_user(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test retrieving a specific user by username."""
        # Arrange
        payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )

        # Act
        created_user = await user_repository.add_user(payload)
        user = await user_repository.get_user_by_username("alice")

        # Assert
        assert user is not None
        assert user.id == created_user.id
        assert user.username == "alice"
        assert user.email == "alice@example.com"

    @pytest.mark.asyncio
    async def test_get_user_by_username_returns_none_when_missing(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test retrieving a non-existent username returns None."""
        # Act
        user = await user_repository.get_user_by_username("missing")

        # Assert
        assert user is None


class TestGetUsers:
    """Tests for SqlaUserRepository.get_users()."""

    @pytest.mark.asyncio
    async def test_get_users_returns_all_users(self, user_repository: SqlaUserRepository) -> None:
        """Test retrieving all users from the repository."""
        # Arrange
        first_payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )
        second_payload = UserCreate(
            username="bob",
            email="bob@example.com",
            full_name="Bob Jones",
            disabled=False,
            hashed_password="hashed-password",
        )

        # Act
        await user_repository.add_user(first_payload)
        await user_repository.add_user(second_payload)
        users = await user_repository.get_users()

        # Assert
        assert len(users) == 2
        assert {user.username for user in users} == {"alice", "bob"}

    @pytest.mark.asyncio
    async def test_get_users_returns_empty_list_when_no_users(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test retrieving users when none exist."""
        # Act
        users = await user_repository.get_users()

        # Assert
        assert users == []


class TestGetUser:
    """Tests for SqlaUserRepository.get_user()."""

    @pytest.mark.asyncio
    async def test_get_user_returns_matching_user(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test retrieving a specific user by ID."""
        # Arrange
        payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )

        # Act
        created_user = await user_repository.add_user(payload)
        user = await user_repository.get_user(created_user.id)

        # Assert
        assert user is not None
        assert user.id == created_user.id
        assert user.username == "alice"

    @pytest.mark.asyncio
    async def test_get_user_returns_none_when_missing(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test retrieving a non-existent user returns None."""
        # Act
        user = await user_repository.get_user(999)

        # Assert
        assert user is None


class TestUpdateUser:
    """Tests for SqlaUserRepository.update_user()."""

    @pytest.mark.asyncio
    async def test_update_user_updates_only_provided_fields(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test updating only specific fields of an existing user."""
        # Arrange
        create_payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )
        update_payload = UserUpdate(full_name="Alice Jones")

        # Act
        created_user = await user_repository.add_user(create_payload)
        updated_user = await user_repository.update_user(created_user.id, update_payload)

        # Assert
        assert updated_user is not None
        assert updated_user.id == created_user.id
        assert updated_user.username == "alice"
        assert updated_user.email == "alice@example.com"
        assert updated_user.full_name == "Alice Jones"
        assert updated_user.disabled is False

    @pytest.mark.asyncio
    async def test_update_user_updates_multiple_fields(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test updating multiple fields of an existing user."""
        # Arrange
        create_payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )
        update_payload = UserUpdate(
            username="alice-jones", email="alice.jones@example.com", disabled=True
        )

        # Act
        created_user = await user_repository.add_user(create_payload)
        updated_user = await user_repository.update_user(created_user.id, update_payload)

        # Assert
        assert updated_user is not None
        assert updated_user.username == "alice-jones"
        assert updated_user.email == "alice.jones@example.com"
        assert updated_user.full_name == "Alice Smith"
        assert updated_user.disabled is True

    @pytest.mark.asyncio
    async def test_update_user_returns_none_when_missing(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test updating a non-existent user returns None."""
        # Arrange
        update_payload = UserUpdate(full_name="Ghost")

        # Act
        updated_user = await user_repository.update_user(999, update_payload)

        # Assert
        assert updated_user is None


class TestDeleteUser:
    """Tests for SqlaUserRepository.delete_user()."""

    @pytest.mark.asyncio
    async def test_delete_user_removes_existing_user(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test successfully deleting an existing user."""
        # Arrange
        payload = UserCreate(
            username="alice",
            email="alice@example.com",
            full_name="Alice Smith",
            disabled=False,
            hashed_password="hashed-password",
        )

        # Act
        created_user = await user_repository.add_user(payload)
        deleted = await user_repository.delete_user(created_user.id)
        user = await user_repository.get_user(created_user.id)

        # Assert
        assert deleted is True
        assert user is None

    @pytest.mark.asyncio
    async def test_delete_user_returns_false_when_missing(
        self, user_repository: SqlaUserRepository
    ) -> None:
        """Test deleting a non-existent user returns False."""
        # Act
        deleted = await user_repository.delete_user(999)

        # Assert
        assert deleted is False
