import pytest

from app.domain.pets import PetCreate, PetUpdate
from app.repositories.pet_repository import SqlaPetRepository


class TestAddPet:
    """Tests for SqlaPetRepository.add_pet()"""

    @pytest.mark.asyncio
    async def test_add_pet_persists_and_returns_pet(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test successfully adding a pet and verifying persistence."""
        # Arrange
        payload = PetCreate(
            name="Milo", species="cat", breed="Siamese", color="cream", owner_name="Charlie", age=3
        )

        # Act
        pet = await pet_repository.add_pet(payload)

        # Assert
        assert pet.id is not None
        assert pet.name == "Milo"
        assert pet.species == "cat"
        assert pet.breed == "Siamese"
        assert pet.color == "cream"
        assert pet.owner_name == "Charlie"
        assert pet.age == 3

    @pytest.mark.asyncio
    async def test_add_pet_returns_pet_with_generated_id(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test that added pet has an ID generated by the database."""
        # Arrange
        payload = PetCreate(
            name="Whiskers",
            species="dog",
            breed="Golden Retriever",
            color="golden",
            owner_name="David",
            age=2,
        )

        # Act
        pet = await pet_repository.add_pet(payload)

        # Assert
        assert pet.id > 0


class TestGetPets:
    """Tests for SqlaPetRepository.get_pets()"""

    @pytest.mark.asyncio
    async def test_get_pets_returns_all_pets(self, pet_repository: SqlaPetRepository) -> None:
        """Test retrieving all pets from the repository."""
        # Arrange
        first_payload = PetCreate(
            name="Milo",
            species="cat",
            breed="Siamese",
            color="cream",
            owner_name="Charlie",
            age=3,
        )
        second_payload = PetCreate(
            name="Bolt",
            species="dog",
            breed="Golden Retriever",
            color="golden",
            owner_name="David",
            age=5,
        )

        # Act
        await pet_repository.add_pet(first_payload)
        await pet_repository.add_pet(second_payload)
        pets = await pet_repository.get_pets()

        # Assert
        assert len(pets) == 2
        assert {pet.name for pet in pets} == {"Milo", "Bolt"}

    @pytest.mark.asyncio
    async def test_get_pets_returns_empty_list_when_no_pets(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test retrieving pets when none exist."""
        # Act
        pets = await pet_repository.get_pets()

        # Assert
        assert pets == []
        assert len(pets) == 0


class TestGetPet:
    """Tests for SqlaPetRepository.get_pet()"""

    @pytest.mark.asyncio
    async def test_get_pet_returns_matching_pet(self, pet_repository: SqlaPetRepository) -> None:
        """Test retrieving a specific pet by ID."""
        # Arrange
        payload = PetCreate(
            name="Milo",
            species="cat",
            breed="Siamese",
            color="cream",
            owner_name="Charlie",
            age=3,
        )

        # Act
        created_pet = await pet_repository.add_pet(payload)
        pet = await pet_repository.get_pet(created_pet.id)

        # Assert
        assert pet is not None
        assert pet.id == created_pet.id
        assert pet.name == "Milo"
        assert pet.species == "cat"

    @pytest.mark.asyncio
    async def test_get_pet_returns_none_when_missing(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test retrieving a non-existent pet returns None."""
        # Act
        pet = await pet_repository.get_pet(999)

        # Assert
        assert pet is None


class TestUpdatePet:
    """Tests for SqlaPetRepository.update_pet()"""

    @pytest.mark.asyncio
    async def test_update_pet_updates_only_provided_fields(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test updating only specific fields of an existing pet."""
        # Arrange
        create_payload = PetCreate(
            name="Milo",
            species="cat",
            breed="Siamese",
            color="cream",
            owner_name="Charlie",
            age=3,
        )
        update_payload = PetUpdate(age=4)

        # Act
        created_pet = await pet_repository.add_pet(create_payload)
        updated_pet = await pet_repository.update_pet(created_pet.id, update_payload)

        # Assert
        assert updated_pet is not None
        assert updated_pet.id == created_pet.id
        assert updated_pet.name == "Milo"
        assert updated_pet.species == "cat"
        assert updated_pet.breed == "Siamese"
        assert updated_pet.color == "cream"
        assert updated_pet.owner_name == "Charlie"
        assert updated_pet.age == 4

    @pytest.mark.asyncio
    async def test_update_pet_updates_multiple_fields(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test updating multiple fields of an existing pet."""
        # Arrange
        create_payload = PetCreate(
            name="Milo",
            species="cat",
            breed="Siamese",
            color="cream",
            owner_name="Charlie",
            age=3,
        )
        update_payload = PetUpdate(name="Mittens", age=5)

        # Act
        created_pet = await pet_repository.add_pet(create_payload)
        updated_pet = await pet_repository.update_pet(created_pet.id, update_payload)

        # Assert
        assert updated_pet is not None
        assert updated_pet.name == "Mittens"
        assert updated_pet.species == "cat"
        assert updated_pet.breed == "Siamese"
        assert updated_pet.color == "cream"
        assert updated_pet.owner_name == "Charlie"
        assert updated_pet.age == 5

    @pytest.mark.asyncio
    async def test_update_pet_returns_none_when_missing(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test updating a non-existent pet returns None."""
        # Arrange
        payload = PetUpdate(name="Ghost")

        # Act
        updated_pet = await pet_repository.update_pet(999, payload)

        # Assert
        assert updated_pet is None


class TestDeletePet:
    """Tests for SqlaPetRepository.delete_pet()"""

    @pytest.mark.asyncio
    async def test_delete_pet_removes_existing_pet(self, pet_repository: SqlaPetRepository) -> None:
        """Test successfully deleting an existing pet."""
        # Arrange
        payload = PetCreate(
            name="Milo",
            species="cat",
            breed="Siamese",
            color="cream",
            owner_name="Charlie",
            age=3,
        )

        # Act
        created_pet = await pet_repository.add_pet(payload)
        deleted = await pet_repository.delete_pet(created_pet.id)
        pet = await pet_repository.get_pet(created_pet.id)

        # Assert
        assert deleted is True
        assert pet is None

    @pytest.mark.asyncio
    async def test_delete_pet_returns_false_when_missing(
        self, pet_repository: SqlaPetRepository
    ) -> None:
        """Test deleting a non-existent pet returns False."""
        # Act
        deleted = await pet_repository.delete_pet(999)

        # Assert
        assert deleted is False
